apiVersion: apps/v1
kind: Deployment
metadata:
  name: preemptible-lifecycle-scheduler
  namespace: hack-tribe
  labels:
    app: preemptible-lifecycle-scheduler
    squad: governance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preemptible-lifecycle-scheduler
  template:
    metadata:
      labels:
        app: preemptible-lifecycle-scheduler
        squad: governance
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        warpin: persistent
      containers:
        - image: asia.gcr.io/warung-support/preemptible-lifecycle-scheduler-prod:latest
          name: preemptible-lifecycle-scheduler
          imagePullPolicy: Always
          volumeMounts:
            - name: preemptible-lifecycle-scheduler-config
              mountPath: /home/app/config
              readOnly: true
      imagePullSecrets:
        - name: gcr-json-key

      volumes:
        - name: preemptible-lifecycle-scheduler-config
          secret:
            secretName: preemptible-lifecycle-scheduler-config