apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: preemptible-lifecycle-scheduler
  name: preemptible-lifecycle-scheduler
  namespace: hack-tribe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: preemptible-lifecycle-scheduler
subjects:
  - kind: ServiceAccount
    name: preemptible-lifecycle-scheduler
    namespace: hack-tribe