apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: preemptible-lifecycle-scheduler
  name: preemptible-lifecycle-scheduler
  namespace: hack-tribe
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - nodes
    verbs:
      - list
      - get
      - delete