apiVersion: v1
kind: Secret
metadata:
  name: preemptible-lifecycle-scheduler-config
  namespace: hack-tribe
  labels:
    app: preemptible-lifecycle-scheduler
type: Opaque
stringData:
  config.yaml: |-
    environment: "production"

    peak-hour-ranges:
      - "03:00-23:00"
