apiVersion: v1
kind: Secret
metadata:
  name: preemptible-lifecycle-scheduler-config
  namespace: hack-tribe
  labels:
    app: preemptible-lifecycle-scheduler
type: Opaque
stringData:
  config.yaml: |-
    environment: "production"

    peak-hour-ranges:
      - "04:00-21:00"

    # graceful shutdown period in minute
    graceful-period: 15
